title: Hamilton
description: A minimal and beautiful Jekyll theme best for writing and note-taking.
author: cose101
avatar: /logo.gif
email: gmail@gmail.com
skin: daylight

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: twitter_username
  card: summary
logo: logo.gif
social:
  name: social name
  links:
    - https://twitter.com
    - https://www.facebook.com
    - https://github.com/cose101
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
